apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-nodejs-app
  title: Node.js Backend Service
  description: Scaffolds a Node.js backend microservice with best practices.
spec:
  owner: platform-engineering
  type: service
  parameters:
    - title: OpenCode Environment
      required:
        - namespace
        - api-secrets-name
        - configmap-name
      properties:
        namespace:
          title: Environment Name
          type: string
          description: Namespace to create and deploy.
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        api-secrets-name:
          title: Secrets Name
          type: string
          description: Name of secrets containing API keys to use
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        configmap-name:
          title: Environment Configuration
          type: string
          description: Namespace of config map containing opencode configuration files
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'


  steps:
    - id: generateSource
      name: Generate Node.js Application Codebase
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          name: ${{ parameters.name }}
          owner: user:default/${{ user.entity.metadata.name }}

    - id: publishSource
      name: Create GitHub Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: github.com?owner=your-org&repo=${{ parameters.name }}
        defaultBranch: main
        sourcePath: ./source

  output:
    links:
      - title: View the Repository
        url: ${{ steps.publishSource.output.remoteUrl }}