# Default values for opencode-devworkspace chart

# DevWorkspace configuration
devworkspace:
  name: opencode-dsp
  routingClass: che
  started: true

# DevWorkspace Template configuration
devworkspaceTemplate:
  name: opencode-dsp-tpl
  namespace: openshift-operators
  generation: 1
  install: true

# Container resources
resources:
  tooling:
    cpuLimit: 4000m
    cpuRequest: 1000m
    memoryLimit: 6G
    memoryRequest: 500Mi
  cheCodeInjector:
    cpuLimit: 500m
    cpuRequest: 30m
    memoryLimit: 256Mi
    memoryRequest: 32Mi
  cheCodeRuntime:
    cpuLimit: 500m
    cpuRequest: 30m
    memoryLimit: 1024Mi
    memoryRequest: 256Mi

# Images
images:
  tooling: quay.io/noeloc/opencode:latest-experiment
  cheCodeInjector: registry.redhat.io/devspaces/code-rhel9@sha256:7b68bf06abf4f2b948d21ffa82401b44f26965b093e4875653344ae2b7fe46c8
  cheCodeRuntime: registry.redhat.io/devspaces/udi-rhel9@sha256:bb5baa05f316944ca6df56ad718c368b248e8f4b2488551549b1b13c4ed5844b

# URLs and configuration
urls:
  devspacesURL: https://devspaces.apps.snoai.example.com
  cheDashboard: https://devspaces.apps.snoai.example.com
  chePluginRegistry: https://devspaces.apps.snoai.example.com/plugin-registry/v3
  chePluginRegistryInternal: http://plugin-registry.openshift-operators.svc:8080/v3
  clusterConsole: https://console-openshift-console.apps.snoai.example.com
  clusterConsoleTitle: OpenShift console
  openvsxRegistry: ""

# OpenCode ConfigMap configuration
opencodeConfig:
  autoupdate: false
  instructions:
    - AGENTS.md
    - docs/guidelines.md
  enabled_providers:
    - RH-MAAS
    - LLAMASTACK
    - opencode-zen
    - openrouter
  mcp:
    remote-skills:
      type: remote
      url: '{env:CLAUDE_SKILLS_MCP_URL}'
    context7:
      type: remote
      url: 'https://mcp.context7.com/mcp'
      headers:
        CONTEXT7_API_KEY: '{env:CONTEXT7_API_KEY}'
    gh_grep:
      type: remote
      url: 'https://mcp.grep.app'
    openshift-mcp:
      type: remote
      url: 'http://kubernetes-mcp-server.mcptest.svc.cluster.local:8080/mcp'
    prometheus-mcp:
      type: remote
      url: 'http://prom-mcp.skills.svc.cluster.local:8080/mcp'
  keybinds:
    command_list: ctrl+l
  provider:
    openrouter:
      options:
        OPENROUTER_API_KEY: '{env:OPENROUTER_API_KEY}'
      models:
        moonshotai/kimi-k2:
          options:
            provider:
              order:
                - baseten
              allow_fallbacks: false
    opencode-zen:
      npm: '@ai-sdk/openai-compatible'
      name: opencode-zen
      options:
        baseURL: 'https://opencode.ai/zen/v1'
      models:
        big-pickle:
          name: big-pickle
        glm-4.7-free:
          name: glm-4.7-free
        grok-code:
          name: grok-code
    RH-MAAS:
      npm: '@ai-sdk/openai-compatible'
      name: RH-MAAS-Llama-3.2-3B-Instruct
      options:
        baseURL: '{env:RH_MAAS_URL}'
        apiKey: '{env:RH_MAAS_Llama_3_2_3B_Instruct_API_KEY}'
      models:
        llama-3-2-3b:
          name: llama-3-2-3b
          limit:
            context: 120000
            output: 120000
    LLAMASTACK:
      npm: '@ai-sdk/openai-compatible'
      name: llama-stack
      options:
        baseURL: '{env:OPENCODE_LLS_URL}'
      models:
        llama-4-scout-17b-16e-w4a16:
          name: llama-4-scout-17b-16e-w4a16
          limit:
            context: 120000
            output: 120000
        microsoft/phi-4:
          name: microsoft/phi-4
          limit:
            context: 120000
            output: 120000

# Environment variables for secret
envSecrets:
  CLAUDE_SKILLS_MCP_URL: http://claude-skills-mcp-backend-skills.apps.example.com/mcp
  CONTEXT7_API_KEY: ctx7sk-e266f6asdfsdfsdf
  OPENCODE_LLS_URL: http://llama-stack-service-opencode.apps.example.com/v1/openai/v1
  RH_MAAS_Llama_3_2_3B_Instruct_API_KEY: 64509asdfsdfsdf
  RH_MAAS_URL: https://llama-production.apps.example.com:443/v1
  OPENROUTER_API_KEY: scvccfdgdfg

# VS Code Editor Config
vscodeConfig:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "github.vscode-pull-request-github"
  settings:
    gitDefaultCloneDirectory: "/projects/"
    windowHeader: "OpenCode Agentic AI Command Line Interface"
    windowCommandCenter: false
    terminalIntegratedDefaultLocation: "editor"
    terminalIntegratedConfirmOnExit: "always"
    terminalIntegratedCwd: "/projects"
    terminalIntegratedDefaultProfileLinux: "bash (2)"
    workbenchColorCustomizations:
      titleBarActiveBackground: "#CCA700"
      titleBarActiveForeground: "#ffffff"

# Git SSH Key Secret configuration
gitSshKey:
  name: git-ssh-key
  mountPath: /etc/ssh/
  sshKey: ""
  sshKeyPub: ""
  passphrase: ""
  sshConfig: |+
    host *
      IdentityFile /etc/ssh/dwo_ssh_key
      StrictHostKeyChecking = no
  enabled: true