# Default values for opencode-devworkspace chart

# DevWorkspace configuration
devworkspace:
  name: opencode-dsp
  routingClass: che
  started: true

# DevWorkspace Template configuration
devworkspaceTemplate:
  name: opencode-dsp-tpl
  namespace: openshift-operators
  generation: 1
  install: true

# Container resources
resources:
  tooling:
    cpuLimit: 4000m
    cpuRequest: 1000m
    memoryLimit: 6G
    memoryRequest: 500Mi
  cheCodeInjector:
    cpuLimit: 500m
    cpuRequest: 30m
    memoryLimit: 256Mi
    memoryRequest: 32Mi
  cheCodeRuntime:
    cpuLimit: 500m
    cpuRequest: 30m
    memoryLimit: 1024Mi
    memoryRequest: 256Mi

# Images
images:
  tooling: quay.io/noeloc/opencode:latest-experiment
  cheCodeInjector: registry.redhat.io/devspaces/code-rhel9@sha256:7b68bf06abf4f2b948d21ffa82401b44f26965b093e4875653344ae2b7fe46c8
  cheCodeRuntime: registry.redhat.io/devspaces/udi-rhel9@sha256:bb5baa05f316944ca6df56ad718c368b248e8f4b2488551549b1b13c4ed5844b

# URLs and configuration
urls:
  devspacesURL: https://devspaces.apps.snoai.example.com
  cheDashboard: https://devspaces.apps.snoai.example.com
  chePluginRegistry: https://devspaces.apps.snoai.example.com/plugin-registry/v3
  chePluginRegistryInternal: http://plugin-registry.openshift-operators.svc:8080/v3
  clusterConsole: https://console-openshift-console.apps.snoai.example.com
  clusterConsoleTitle: OpenShift console
  openvsxRegistry: ""

# Environment variables for secret
envSecrets:
  CLAUDE_SKILLS_MCP_URL: http://claude-skills-mcp-backend-skills.apps.example.com/mcp
  CONTEXT7_API_KEY: ctx7sk-e266f6asdfsdfsdf
  OPENCODE_LLS_URL: http://llama-stack-service-opencode.apps.example.com/v1/openai/v1
  RH_MAAS_Llama_3_2_3B_Instruct_API_KEY: 64509asdfsdfsdf
  RH_MAAS_URL: https://llama-production.apps.example.com:443/v1
  OPENROUTER_API_KEY: scvccfdgdfg

# VS Code Editor Config
vscodeConfig:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "github.vscode-pull-request-github"
  settings:
    gitDefaultCloneDirectory: "/projects/"
    windowHeader: "Agentic AI Developer Environment"
    windowCommandCenter: false
    terminalIntegratedDefaultLocation: "editor"
    terminalIntegratedConfirmOnExit: "always"
    terminalIntegratedCwd: "/projects"
    terminalIntegratedDefaultProfileLinux: "bash (2)"
    workbenchColorCustomizations:
      titleBarActiveBackground: "#5F0000"
      titleBarActiveForeground: "#ffffff"

# Git SSH Key Secret configuration
gitSshKey:
  name: git-ssh-key
  mountPath: /etc/ssh/
  sshKey: ""
  sshKeyPub: ""
  passphrase: ""
  sshConfig: |+
    host *
      IdentityFile /etc/ssh/dwo_ssh_key
      StrictHostKeyChecking = no
  enabled: true