{{- if .Values.gitSshKey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitSshKey.name }}
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: {{ .Values.gitSshKey.mountPath }}
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-secret: "true"
type: Opaque
data:
  dwo_ssh_key: {{ .Values.gitSshKey.sshKey | b64enc }}
  dwo_ssh_key.pub: {{ .Values.gitSshKey.sshKeyPub | b64enc }}
  passphrase: {{ .Values.gitSshKey.passphrase | b64enc }}
  ssh_config: {{ .Values.gitSshKey.sshConfig | b64enc }}
{{- end }}
