apiVersion: v1
data: 
{{- with .Values.envSecrets }}
  CLAUDE_SKILLS_MCP_URL: {{ .CLAUDE_SKILLS_MCP_URL | b64enc}}
  CONTEXT7_API_KEY: {{ .CONTEXT7_API_KEY | b64enc}}
  OPENCODE_LLS_URL: {{ .OPENCODE_LLS_URL | b64enc}}
  RH_MAAS_Llama_3_2_3B_Instruct_API_KEY: {{ .RH_MAAS_Llama_3_2_3B_Instruct_API_KEY | b64enc}}
  RH_MAAS_URL: {{ .RH_MAAS_URL | b64enc}}
  OPENROUTER_API_KEY: {{ .OPENROUTER_API_KEY | b64enc}}
{{- end }}
kind: Secret
metadata:
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-secret: "true"
  name: opencode-env-secret
  namespace: {{ .Release.Namespace }}
type: Opaque