apiVersion: v1
data:
  opencode.json: |
{{ .Files.Get "opencode.json" | indent 4 }}
  tui.json: |
{{ .Files.Get "tui.json" | indent 4 }}
kind: ConfigMap
metadata:
  annotations:
    controller.devfile.io/mount-path: /home/user/opencode/config-map
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  name: opencode-config
  namespace: {{ .Release.Namespace }}