apiVersion: v1
data: 
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-secret: "true"
  name: opencode-env-secret
  namespace: {{ .Release.Namespace }}
type: Opaque